compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0006
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard
  - code: YN0060
    level: discard
  - code: YN0057
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.2.2.cjs
