[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
solidr = "9yRToMqBifuubLRmssBnHW6v3Jv1QZGZ25tRqYgrzttQ"

[programs.devnet]
solidr = "9yRToMqBifuubLRmssBnHW6v3Jv1QZGZ25tRqYgrzttQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/opt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"

[workspace]
types = "client/types/"
