[package]
name = "solidr"
version = "0.1.0"
description = "The decentralized application for simple sharing expenses"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solidr"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
verbose = []

[dependencies]
anchor-lang = {version = "0.30.1", features = ["init-if-needed"]}
sha2 = {version = "0.10.8" }
