# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prod Continuous integration
env:
    VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
    VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: tchambard/solana-test-validator:solana_1.18.16-anchor_0.30.1
            options: --user root
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v3

            - name: Yarn cache
              uses: Andrews-McMeel-Universal/cache-yarn-install@v1
              with:
                  enable-corepack: true
                  cache-node-modules: true
                  cache-install-state: true

            - name: Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: |
                      packages/programs/solidr-program

            - name: Init solana-test-validator-docker tool
              run: |
                  echo "{\"imageName\": \"tchambard/solana-test-validator:latest\", \"containerName\": \"solana-test-validator\", \"bypassLocalExe\": true }" >> .solrc

            - name: Lint
              run: |
                  yarn run lint-all

            - name: Compile
              run: |
                  yarn run compile-all

            - name: Test
              run: |
                  yarn run test-all

            - name: Install Vercel CLI
              run: npm install -g vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
              working-directory: packages/fronts/solidr-front-dapp

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
              working-directory: packages/fronts/solidr-front-dapp

            - name: Deploy Project Artifacts Production to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
              working-directory: packages/fronts/solidr-front-dapp
